export interface ToolConfig {
  id: string
  accent: string
  name: string
  nameEn: string
  description: string
  descriptionEn: string
  category: string
  icon: string
  path: string
  keywords: string[]
  priority: number
}

export const tools: ToolConfig[] = [
  {
    id: 'json-formatter',
    accent: 'cyan',
    nameEn: 'JSON Formatter',
    name: 'JSON 格式化',
    description: '格式化、压缩、验证 JSON 数据',
    descriptionEn: 'Format, minify and validate JSON data',
    category: 'text',
    icon: 'Braces',
    path: '/tools/json',
    keywords: ['json', '格式化', '格式', '验证'],
    priority: 1,
  },
  {
    id: 'base64-encoder',
    accent: 'lime',
    nameEn: 'Base64 Codec',
    name: 'Base64 编解码',
    description: 'Base64 编码与解码，支持文本和图片',
    descriptionEn: 'Base64 encode/decode for text and images',
    category: 'encoder',
    icon: 'FileCode',
    path: '/tools/base64',
    keywords: ['base64', '编码', '解码'],
    priority: 2,
  },
  {
    id: 'timestamp-converter',
    accent: 'purple',
    nameEn: 'Timestamp Converter',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期时间互转',
    descriptionEn: 'Convert Unix timestamps to dates and back',
    category: 'datetime',
    icon: 'Clock',
    path: '/tools/timestamp',
    keywords: ['timestamp', '时间戳', '日期'],
    priority: 3,
  },
  {
    id: 'regex-tester',
    accent: 'amber',
    nameEn: 'Regex Tester',
    name: '正则表达式测试',
    description: '实时测试正则表达式，查看匹配结果',
    descriptionEn: 'Test regular expressions live with match results',
    category: 'developer',
    icon: 'Regex',
    path: '/tools/regex',
    keywords: ['regex', '正则', '表达式', '测试'],
    priority: 4,
  },
  {
    id: 'hash-generator',
    accent: 'magenta',
    nameEn: 'Hash & UUID',
    name: '哈希 & UUID 生成',
    description: 'MD5/SHA 哈希生成、UUID v4 生成',
    descriptionEn: 'MD5/SHA hashing and UUID v4 generation',
    category: 'developer',
    icon: 'Hash',
    path: '/tools/uuid',
    keywords: ['hash', 'md5', 'sha', 'uuid', '哈希'],
    priority: 5,
  },
  {
    id: 'url-encoder',
    accent: 'pink',
    nameEn: 'URL Codec',
    name: 'URL 编解码',
    description: 'URL 编码、解码与解析',
    descriptionEn: 'URL encode, decode and parse',
    category: 'encoder',
    icon: 'Link2',
    path: '/tools/url',
    keywords: ['url', '编码', '解码', '解析'],
    priority: 6,
  },
  {
    id: 'markdown-editor',
    accent: 'cyan',
    nameEn: 'Markdown Editor',
    name: 'Markdown 编辑器',
    description: '实时预览 Markdown，支持 GFM 语法',
    descriptionEn: 'Live Markdown preview with GFM support',
    category: 'text',
    icon: 'FileText',
    path: '/tools/markdown',
    keywords: ['markdown', '编辑器', '预览', '文档'],
    priority: 7,
  },
  {
    id: 'color-converter',
    accent: 'lime',
    nameEn: 'Color Converter',
    name: '颜色转换器',
    description: 'HEX、RGB、HSL、RGBA 颜色格式互转',
    descriptionEn: 'HEX, RGB, HSL, RGBA color conversions',
    category: 'frontend',
    icon: 'Palette',
    path: '/tools/color',
    keywords: ['color', '颜色', 'hex', 'rgb', 'hsl', '转换'],
    priority: 8,
  },
  {
    id: 'binary-converter',
    accent: 'purple',
    nameEn: 'Radix Converter',
    name: '进制转换器',
    description: '二进制、十进制、十六进制互转',
    descriptionEn: 'Binary, decimal and hexadecimal conversion',
    category: 'converter',
    icon: 'Hash',
    path: '/tools/binary',
    keywords: ['binary', '进制', '二进制', '十六进制', '转换'],
    priority: 9,
  },
  {
    id: 'qrcode-generator',
    accent: 'amber',
    nameEn: 'QR Design',
    name: '二维码设计',
    description: '内容类型、点阵样式、Logo 与多格式导出',
    descriptionEn: 'Content types, dot styling, logo and multi-format export',
    category: 'developer',
    icon: 'QrCode',
    path: '/tools/qrcode',
    keywords: ['qrcode', '二维码', '生成', 'QR码', 'wifi', '名片', 'vcard', 'logo', '样式', '设计'],
    priority: 10,
  },
  {
    id: 'diff-tool',
    accent: 'magenta',
    nameEn: 'Text Diff',
    name: 'Diff 文本对比',
    description: '对比两段文本的差异',
    descriptionEn: 'Compare two texts side by side',
    category: 'text',
    icon: 'ArrowLeftRight',
    path: '/tools/diff',
    keywords: ['diff', '对比', '差异', '文本对比'],
    priority: 11,
  },
  {
    id: 'curl-generator',
    accent: 'pink',
    nameEn: 'cURL Generator',
    name: 'cURL 命令生成',
    description: '可视化构建 HTTP 请求',
    descriptionEn: 'Build HTTP requests visually, export cURL',
    category: 'network',
    icon: 'Terminal',
    path: '/tools/curl',
    keywords: ['curl', 'http', 'api', '命令', '请求'],
    priority: 12,
  },
  {
    id: 'ip-query',
    accent: 'cyan',
    nameEn: 'IP Lookup',
    name: 'IP 地址查询',
    description: '查询 IP 地址信息和地理位置',
    descriptionEn: 'Query IP address info and geolocation',
    category: 'network',
    icon: 'Globe',
    path: '/tools/ip',
    keywords: ['ip', '地址', '查询', '地理位置', 'ipv4', 'ipv6'],
    priority: 13,
  },
  {
    id: 'jwt-decoder',
    accent: 'lime',
    nameEn: 'JWT Decoder',
    name: 'JWT 解码器',
    description: '解码和验证 JSON Web Token',
    descriptionEn: 'Decode and verify JSON Web Tokens',
    category: 'developer',
    icon: 'Shield',
    path: '/tools/jwt',
    keywords: ['jwt', 'token', '解码', '验证', 'json'],
    priority: 14,
  },
  {
    id: 'sql-formatter',
    accent: 'purple',
    nameEn: 'SQL Formatter',
    name: 'SQL 格式化',
    description: '美化和格式化 SQL 语句',
    descriptionEn: 'Beautify and format SQL statements',
    category: 'developer',
    icon: 'Database',
    path: '/tools/sql',
    keywords: ['sql', '格式化', '美化', '数据库', '查询'],
    priority: 15,
  },
  {
    id: 'data-converter',
    accent: 'amber',
    nameEn: 'Data Converter',
    name: '数据格式转换',
    description: 'JSON、XML、YAML、TOML 格式互转',
    descriptionEn: 'Convert between JSON, XML, YAML and TOML',
    category: 'converter',
    icon: 'RefreshCw',
    path: '/tools/convert',
    keywords: ['json', 'xml', 'yaml', 'toml', '转换', '格式'],
    priority: 16,
  },
  {
    id: 'image-studio',
    accent: 'purple',
    nameEn: 'Image',
    name: '图像',
    description: '调整尺寸、压缩、裁剪、滤镜、水印与格式转换',
    descriptionEn: 'Resize, compress, crop, filter, watermark and convert images',
    category: 'image',
    icon: 'WandSparkles',
    path: '/tools/image-studio',
    keywords: ['图片', '图像', 'image', 'studio', '裁剪', '水印', '滤镜', '格式转换', '压缩', 'resize', 'crop', 'jpg', 'png', 'webp'],
    priority: 17,
  },
  {
    id: 'code-minify',
    accent: 'pink',
    nameEn: 'Code Minifier',
    name: '代码压缩',
    description: '压缩 JavaScript、CSS、HTML 代码',
    descriptionEn: 'Minify JavaScript, CSS and HTML code',
    category: 'developer',
    icon: 'Minimize2',
    path: '/tools/minify',
    keywords: ['代码', '压缩', 'js', 'css', 'html', 'minify'],
    priority: 18,
  },
  {
    id: 'html-entity',
    accent: 'cyan',
    nameEn: 'HTML Entity',
    name: 'HTML 实体编解码',
    description: 'HTML 特殊字符与实体互转',
    descriptionEn: 'Encode and decode HTML entities',
    category: 'encoder',
    icon: 'Code2',
    path: '/tools/html-entity',
    keywords: ['html', '实体', '编码', '解码', '转义'],
    priority: 19,
  },
  {
    id: 'useragent-parser',
    accent: 'lime',
    nameEn: 'User-Agent Parser',
    name: 'User-Agent 解析',
    description: '解析浏览器和设备信息',
    descriptionEn: 'Parse browser and device info',
    category: 'network',
    icon: 'Monitor',
    path: '/tools/useragent',
    keywords: ['useragent', 'ua', '浏览器', '设备', '解析'],
    priority: 20,
  },
  {
    id: 'cron-generator',
    accent: 'purple',
    nameEn: 'Cron Builder',
    name: 'Cron 表达式生成',
    description: '生成和解析 Cron 定时任务表达式',
    descriptionEn: 'Build and explain Cron schedule expressions',
    category: 'developer',
    icon: 'Clock',
    path: '/tools/cron',
    keywords: ['cron', '定时', '任务', '表达式', '调度'],
    priority: 21,
  },
]
