export interface ToolConfig {
  id: string
  name: string
  description: string
  category: string
  icon: string
  path: string
  keywords: string[]
  priority: number
}

export const tools: ToolConfig[] = [
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    description: '格式化、压缩、验证 JSON 数据',
    category: 'text',
    icon: 'Braces',
    path: '/tools/json',
    keywords: ['json', '格式化', '格式', '验证'],
    priority: 1,
  },
  {
    id: 'base64-encoder',
    name: 'Base64 编解码',
    description: 'Base64 编码与解码，支持文本和图片',
    category: 'encoder',
    icon: 'FileCode',
    path: '/tools/base64',
    keywords: ['base64', '编码', '解码'],
    priority: 2,
  },
  {
    id: 'timestamp-converter',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期时间互转',
    category: 'datetime',
    icon: 'Clock',
    path: '/tools/timestamp',
    keywords: ['timestamp', '时间戳', '日期'],
    priority: 3,
  },
  {
    id: 'regex-tester',
    name: '正则表达式测试',
    description: '实时测试正则表达式，查看匹配结果',
    category: 'developer',
    icon: 'Regex',
    path: '/tools/regex',
    keywords: ['regex', '正则', '表达式', '测试'],
    priority: 4,
  },
  {
    id: 'hash-generator',
    name: '哈希 & UUID 生成',
    description: 'MD5/SHA 哈希生成、UUID v4 生成',
    category: 'developer',
    icon: 'Hash',
    path: '/tools/uuid',
    keywords: ['hash', 'md5', 'sha', 'uuid', '哈希'],
    priority: 5,
  },
  {
    id: 'url-encoder',
    name: 'URL 编解码',
    description: 'URL 编码、解码与解析',
    category: 'encoder',
    icon: 'Link2',
    path: '/tools/url',
    keywords: ['url', '编码', '解码', '解析'],
    priority: 6,
  },
  {
    id: 'markdown-editor',
    name: 'Markdown 编辑器',
    description: '实时预览 Markdown，支持 GFM 语法',
    category: 'text',
    icon: 'FileText',
    path: '/tools/markdown',
    keywords: ['markdown', '编辑器', '预览', '文档'],
    priority: 7,
  },
  {
    id: 'color-converter',
    name: '颜色转换器',
    description: 'HEX、RGB、HSL、RGBA 颜色格式互转',
    category: 'frontend',
    icon: 'Palette',
    path: '/tools/color',
    keywords: ['color', '颜色', 'hex', 'rgb', 'hsl', '转换'],
    priority: 8,
  },
  {
    id: 'binary-converter',
    name: '进制转换器',
    description: '二进制、十进制、十六进制互转',
    category: 'converter',
    icon: 'Hash',
    path: '/tools/binary',
    keywords: ['binary', '进制', '二进制', '十六进制', '转换'],
    priority: 9,
  },
  {
    id: 'qrcode-generator',
    name: '二维码生成器',
    description: '生成自定义二维码，支持多种格式',
    category: 'developer',
    icon: 'QrCode',
    path: '/tools/qrcode',
    keywords: ['qrcode', '二维码', '生成', 'QR码'],
    priority: 10,
  },
  {
    id: 'diff-tool',
    name: 'Diff 文本对比',
    description: '对比两段文本的差异',
    category: 'text',
    icon: 'ArrowLeftRight',
    path: '/tools/diff',
    keywords: ['diff', '对比', '差异', '文本对比'],
    priority: 11,
  },
  {
    id: 'curl-generator',
    name: 'cURL 命令生成',
    description: '可视化构建 HTTP 请求',
    category: 'network',
    icon: 'Terminal',
    path: '/tools/curl',
    keywords: ['curl', 'http', 'api', '命令', '请求'],
    priority: 12,
  },
  {
    id: 'ip-query',
    name: 'IP 地址查询',
    description: '查询 IP 地址信息和地理位置',
    category: 'network',
    icon: 'Globe',
    path: '/tools/ip',
    keywords: ['ip', '地址', '查询', '地理位置', 'ipv4', 'ipv6'],
    priority: 13,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT 解码器',
    description: '解码和验证 JSON Web Token',
    category: 'developer',
    icon: 'Shield',
    path: '/tools/jwt',
    keywords: ['jwt', 'token', '解码', '验证', 'json'],
    priority: 14,
  },
  {
    id: 'sql-formatter',
    name: 'SQL 格式化',
    description: '美化和格式化 SQL 语句',
    category: 'developer',
    icon: 'Database',
    path: '/tools/sql',
    keywords: ['sql', '格式化', '美化', '数据库', '查询'],
    priority: 15,
  },
  {
    id: 'data-converter',
    name: '数据格式转换',
    description: 'JSON、XML、YAML、TOML 格式互转',
    category: 'converter',
    icon: 'RefreshCw',
    path: '/tools/convert',
    keywords: ['json', 'xml', 'yaml', 'toml', '转换', '格式'],
    priority: 16,
  },
  {
    id: 'image-compress',
    name: '图片压缩',
    description: '在线压缩图片，减小文件大小',
    category: 'image',
    icon: 'Image',
    path: '/tools/image-compress',
    keywords: ['图片', '压缩', '优化', 'jpg', 'png'],
    priority: 17,
  },
  {
    id: 'code-minify',
    name: '代码压缩',
    description: '压缩 JavaScript、CSS、HTML 代码',
    category: 'developer',
    icon: 'Minimize2',
    path: '/tools/minify',
    keywords: ['代码', '压缩', 'js', 'css', 'html', 'minify'],
    priority: 18,
  },
  {
    id: 'html-entity',
    name: 'HTML 实体编解码',
    description: 'HTML 特殊字符与实体互转',
    category: 'encoder',
    icon: 'Code2',
    path: '/tools/html-entity',
    keywords: ['html', '实体', '编码', '解码', '转义'],
    priority: 19,
  },
  {
    id: 'useragent-parser',
    name: 'User-Agent 解析',
    description: '解析浏览器和设备信息',
    category: 'network',
    icon: 'Monitor',
    path: '/tools/useragent',
    keywords: ['useragent', 'ua', '浏览器', '设备', '解析'],
    priority: 20,
  },
  {
    id: 'cron-generator',
    name: 'Cron 表达式生成',
    description: '生成和解析 Cron 定时任务表达式',
    category: 'developer',
    icon: 'Clock',
    path: '/tools/cron',
    keywords: ['cron', '定时', '任务', '表达式', '调度'],
    priority: 21,
  },
]
